# Generated by Django 5.2.7 on 2025-11-25 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('popularity', models.FloatField(default=0)),
                ('type', models.CharField(default='movie', max_length=10)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.JSONField(default=list)),
                ('popularity', models.FloatField(default=0)),
                ('type', models.CharField(default='tv', max_length=10)),
                ('total_seasons', models.IntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=20, unique=True)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=20)),
                ('content_type', models.CharField(max_length=10)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_id', 'content_type')},
            },
        ),
    ]
