# Generated by Django 5.2.7 on 2025-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='contains_spoilers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrating',
            name='review_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
